#!/bin/bash


# $1 indicates the date folder to be processed.
date=$1

# Copy measureCam files into date folder and rename appropriately.
for measureCam in /om/user/kmaher/data/circle_videos/measureCam*; do
	cp $measureCam /om/user/kmaher/data/circle_videos/$date
	mv /om/user/kmaher/data/circle_videos/$date/${measureCam##*/} /om/user/kmaher/data/circle_videos/$date/${date}_${measureCam##*/};
done

# Loop through .avi files and submit processing jobs
for vid in /om/user/kmaher/data/circle_videos/$1/*_Cam?.avi; do
	sbatch /om/user/kmaher/scripts/matlab/circle/subcircle $vid
done
