#!/bin/bash
#
#SBATCH --output=/om/user/kmaher/log/subcircle_%j.txt
#SBATCH -n1
#SBATCH --job-name=subcircle_j%
#SBATCH --nodes=1
#SBATCH --mem=40000
#SBATCH --time=40:00:00

# $1: Name of video
#echo $1
filename="$1"
vidname=${filename##*/}
#echo $vidname

# Parse date and cam number info from video filename.
date=${vidname%%_*}
cam_dot_avi=${vidname##*_}
#cam=${cam_dot_avi%%.*}
#echo $date
#echo $cam_dot_avi

###################################### REVISIT WHEN STREAMPIX ROI STANDARDIZED ##########################################
# Change to relevant folder and copy/rename relevant measureCam and Ring files to this folder.
#cd /om/user/kmaher/data/circle_videos/$date
#cp /om/user/kmaher/data/circle_videos/measure${cam}.avi .
#cp /om/user/kmaher/data/circle_videos/measure${cam}.Ring.mat .
#mv measure${cam}.avi ${date}_measure${cam}.avi
#mv measure${cam}.Ring.mat ${date}_measure${cam}.Ring.mat

# Load matlab and launch tracker command.
module add mit/matlab/2014a
cd /om/user/kmaher/data/circle_videos/$date
matlab -nodisplay -r "addpath(genpath('/om/user/kmaher/scripts/matlab/circle/MATLAB')), addpath(genpath('/om/user/kmaher/data/circle_videos')), disp('${date}_measure${cam_dot_avi}'), TrackerAutomatedScript2('$vidname', 'scale', '${date}_measure${cam_dot_avi}', 'NumWorms', [30, 80]), exit;" 
